// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
   TRelationship extends
      | prismic.CustomTypeModelFetchCustomTypeLevel1
      | prismic.CustomTypeModelFetchCustomTypeLevel2
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2,
   TData extends Record<
      string,
      prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
   >,
   TLang extends string,
> =
   // Content relationship fields
   {
      [TSubRelationship in Extract<
         TRelationship['fields'][number],
         prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship['id']]: ContentRelationshipFieldWithData<TSubRelationship['customtypes'], TLang>;
   } & // Group
   {
      [TGroup in Extract<
         TRelationship['fields'][number],
         prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
         ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
         : never;
   } & // Other fields
   {
      [TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
         ? TData[TFieldKey]
         : never;
   };

type ContentRelationshipFieldWithData<
   TCustomType extends
      | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
      | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
   TLang extends string = string,
> = {
   [ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
      ID,
      TLang,
      PickContentRelationshipFieldData<
         Extract<TCustomType[number], { id: ID }>,
         Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
         TLang
      >
   >;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Content for Buttons variant documents
 */
interface ButtonsVariantDocumentData {
   /**
    * Variant field in *Buttons variant*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: buttons_variant.variant
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/text
    */
   variant: prismic.KeyTextField;
}

/**
 * Buttons variant document from Prismic
 *
 * - **API ID**: `buttons_variant`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonsVariantDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
   Simplify<ButtonsVariantDocumentData>,
   'buttons_variant',
   Lang
>;

/**
 * Item in *Layout → Button link*
 */
export interface LayoutDocumentDataButtonLinkItem {
   /**
    * Link field in *Layout → Button link*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: layout.button_link[].link
    * - **Documentation**: https://prismic.io/docs/fields/link
    */
   link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

   /**
    * Icon field in *Layout → Button link*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: layout.button_link[].icon
    * - **Documentation**: https://prismic.io/docs/fields/image
    */
   icon: prismic.ImageField<never>;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
   /**
    * Button link field in *Layout*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: layout.button_link[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
    */
   button_link: prismic.GroupField<Simplify<LayoutDocumentDataButtonLinkItem>>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
   Simplify<LayoutDocumentData>,
   'layout',
   Lang
>;

type PagesDocumentDataSlicesSlice = AboutMeBlockSlice | ContactMeBlockSlice | TechnologiesBlockSlice | TextBlockSlice;

/**
 * Content for Pages documents
 */
interface PagesDocumentData {
   /**
    * Url field in *Pages*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: pages.url
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/text
    */
   url: prismic.KeyTextField;

   /**
    * Slice Zone field in *Pages*
    *
    * - **Field Type**: Slice Zone
    * - **Placeholder**: *None*
    * - **API ID Path**: pages.slices[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/slices
    */
   slices: prismic.SliceZone<PagesDocumentDataSlicesSlice> /**
    * Meta Title field in *Pages*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A title of the page used for social media and search engines
    * - **API ID Path**: pages.meta_title
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/fields/text
    */;
   meta_title: prismic.KeyTextField;

   /**
    * Meta Description field in *Pages*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A brief summary of the page
    * - **API ID Path**: pages.meta_description
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/fields/text
    */
   meta_description: prismic.KeyTextField;
}

/**
 * Pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
   Simplify<PagesDocumentData>,
   'pages',
   Lang
>;

/**
 * Content for Technologies documents
 */
interface TechnologiesDocumentData {
   /**
    * Text field in *Technologies*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies.text
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/text
    */
   text: prismic.KeyTextField;

   /**
    * Icon field in *Technologies*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies.icon
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/image
    */
   icon: prismic.ImageField<never>;

   /**
    * Level field in *Technologies*
    *
    * - **Field Type**: Select
    * - **Placeholder**: *None*
    * - **Default Value**: low
    * - **API ID Path**: technologies.level
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/select
    */
   level: prismic.SelectField<'low' | 'medium' | 'high', 'filled'>;
}

/**
 * Technologies document from Prismic
 *
 * - **API ID**: `technologies`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologiesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
   Simplify<TechnologiesDocumentData>,
   'technologies',
   Lang
>;

/**
 * Item in *Technologies Card → Technologies data*
 */
export interface TechnologiesCardDocumentDataTechnologiesDataItem {
   /**
    * Technologies item field in *Technologies Card → Technologies data*
    *
    * - **Field Type**: Content Relationship
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_card.technologies_data[].technologies_item
    * - **Documentation**: https://prismic.io/docs/fields/content-relationship
    */
   technologies_item: ContentRelationshipFieldWithData<[{ id: 'technologies'; fields: ['icon', 'text'] }]>;
}

/**
 * Content for Technologies Card documents
 */
interface TechnologiesCardDocumentData {
   /**
    * Label field in *Technologies Card*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_card.label
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/text
    */
   label: prismic.KeyTextField;

   /**
    * Technologies data field in *Technologies Card*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_card.technologies_data[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
    */
   technologies_data: prismic.GroupField<Simplify<TechnologiesCardDocumentDataTechnologiesDataItem>>;
}

/**
 * Technologies Card document from Prismic
 *
 * - **API ID**: `technologies_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologiesCardDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
   Simplify<TechnologiesCardDocumentData>,
   'technologies_card',
   Lang
>;

export type AllDocumentTypes =
   | ButtonsVariantDocument
   | LayoutDocument
   | PagesDocument
   | TechnologiesDocument
   | TechnologiesCardDocument;

/**
 * Primary content in *AboutMeBlock → Default → Primary*
 */
export interface AboutMeBlockSliceDefaultPrimary {
   /**
    * Title field in *AboutMeBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: about_me_block.default.primary.title
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   title: prismic.RichTextField;

   /**
    * Link field in *AboutMeBlock → Default → Primary*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: about_me_block.default.primary.link
    * - **Documentation**: https://prismic.io/docs/fields/link
    */
   link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

   /**
    * Button variant field in *AboutMeBlock → Default → Primary*
    *
    * - **Field Type**: Content Relationship
    * - **Placeholder**: *None*
    * - **API ID Path**: about_me_block.default.primary.button_variant
    * - **Documentation**: https://prismic.io/docs/fields/content-relationship
    */
   button_variant: ContentRelationshipFieldWithData<[{ id: 'buttons_variant'; fields: ['variant'] }]>;

   /**
    * Left card text data field in *AboutMeBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: about_me_block.default.primary.left_card_text_data
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   left_card_text_data: prismic.RichTextField;
}

/**
 * Default variation for AboutMeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutMeBlockSliceDefault = prismic.SharedSliceVariation<
   'default',
   Simplify<AboutMeBlockSliceDefaultPrimary>,
   never
>;

/**
 * Slice variation for *AboutMeBlock*
 */
type AboutMeBlockSliceVariation = AboutMeBlockSliceDefault;

/**
 * AboutMeBlock Shared Slice
 *
 * - **API ID**: `about_me_block`
 * - **Description**: AboutMeBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutMeBlockSlice = prismic.SharedSlice<'about_me_block', AboutMeBlockSliceVariation>;

/**
 * Primary content in *ContactMeBlock → Default → Primary*
 */
export interface ContactMeBlockSliceDefaultPrimary {
   /**
    * Title field in *ContactMeBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: contact_me_block.default.primary.title
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   title: prismic.RichTextField;

   /**
    * Description field in *ContactMeBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: contact_me_block.default.primary.description
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   description: prismic.RichTextField;

   /**
    * Button link field in *ContactMeBlock → Default → Primary*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: contact_me_block.default.primary.button_link
    * - **Documentation**: https://prismic.io/docs/fields/link
    */
   button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

   /**
    * Button variant field in *ContactMeBlock → Default → Primary*
    *
    * - **Field Type**: Content Relationship
    * - **Placeholder**: *None*
    * - **API ID Path**: contact_me_block.default.primary.button_variant
    * - **Documentation**: https://prismic.io/docs/fields/content-relationship
    */
   button_variant: ContentRelationshipFieldWithData<[{ id: 'buttons_variant'; fields: ['variant'] }]>;
}

/**
 * Default variation for ContactMeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactMeBlockSliceDefault = prismic.SharedSliceVariation<
   'default',
   Simplify<ContactMeBlockSliceDefaultPrimary>,
   never
>;

/**
 * Slice variation for *ContactMeBlock*
 */
type ContactMeBlockSliceVariation = ContactMeBlockSliceDefault;

/**
 * ContactMeBlock Shared Slice
 *
 * - **API ID**: `contact_me_block`
 * - **Description**: ContactMeBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactMeBlockSlice = prismic.SharedSlice<'contact_me_block', ContactMeBlockSliceVariation>;

/**
 * Item in *TechnologiesBlock → Default → Primary → Cards*
 */
export interface TechnologiesBlockSliceDefaultPrimaryCardsItem {
   /**
    * Technologies field in *TechnologiesBlock → Default → Primary → Cards*
    *
    * - **Field Type**: Content Relationship
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_block.default.primary.cards[].technologies
    * - **Documentation**: https://prismic.io/docs/fields/content-relationship
    */
   technologies: ContentRelationshipFieldWithData<
      [
         {
            id: 'technologies_card';
            fields: [
               'label',
               {
                  id: 'technologies_data';
                  fields: [
                     {
                        id: 'technologies_item';
                        customtypes: [{ id: 'technologies'; fields: ['icon', 'text', 'level'] }];
                     },
                  ];
               },
            ];
         },
      ]
   >;
}

/**
 * Primary content in *TechnologiesBlock → Default → Primary*
 */
export interface TechnologiesBlockSliceDefaultPrimary {
   /**
    * Title field in *TechnologiesBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_block.default.primary.title
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   title: prismic.RichTextField;

   /**
    * Cards field in *TechnologiesBlock → Default → Primary*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: technologies_block.default.primary.cards[]
    * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
    */
   cards: prismic.GroupField<Simplify<TechnologiesBlockSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for TechnologiesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TechnologiesBlockSliceDefault = prismic.SharedSliceVariation<
   'default',
   Simplify<TechnologiesBlockSliceDefaultPrimary>,
   never
>;

/**
 * Slice variation for *TechnologiesBlock*
 */
type TechnologiesBlockSliceVariation = TechnologiesBlockSliceDefault;

/**
 * TechnologiesBlock Shared Slice
 *
 * - **API ID**: `technologies_block`
 * - **Description**: TechnologiesBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TechnologiesBlockSlice = prismic.SharedSlice<'technologies_block', TechnologiesBlockSliceVariation>;

/**
 * Item in *TextBlock → Default → Primary → Buttons group*
 */
export interface TextBlockSliceDefaultPrimaryButtonsGroupItem {
   /**
    * Link field in *TextBlock → Default → Primary → Buttons group*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.buttons_group[].link
    * - **Documentation**: https://prismic.io/docs/fields/link
    */
   link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

   /**
    * Button variant field in *TextBlock → Default → Primary → Buttons group*
    *
    * - **Field Type**: Content Relationship
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.buttons_group[].button_variant
    * - **Documentation**: https://prismic.io/docs/fields/content-relationship
    */
   button_variant: ContentRelationshipFieldWithData<[{ id: 'buttons_variant'; fields: ['variant'] }]>;
}

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
   /**
    * Title field in *TextBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.title
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   title: prismic.RichTextField;

   /**
    * Description field in *TextBlock → Default → Primary*
    *
    * - **Field Type**: Rich Text
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.description
    * - **Documentation**: https://prismic.io/docs/fields/rich-text
    */
   description: prismic.RichTextField;

   /**
    * Image field in *TextBlock → Default → Primary*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.image
    * - **Documentation**: https://prismic.io/docs/fields/image
    */
   image: prismic.ImageField<never>;

   /**
    * Buttons group field in *TextBlock → Default → Primary*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: text_block.default.primary.buttons_group[]
    * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
    */
   buttons_group: prismic.GroupField<Simplify<TextBlockSliceDefaultPrimaryButtonsGroupItem>>;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
   'default',
   Simplify<TextBlockSliceDefaultPrimary>,
   never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;

declare module '@prismicio/client' {
   interface CreateClient {
      (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
   }

   interface CreateWriteClient {
      (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
   }

   interface CreateMigration {
      (): prismic.Migration<AllDocumentTypes>;
   }

   namespace Content {
      export type {
         ButtonsVariantDocument,
         ButtonsVariantDocumentData,
         LayoutDocument,
         LayoutDocumentData,
         LayoutDocumentDataButtonLinkItem,
         PagesDocument,
         PagesDocumentData,
         PagesDocumentDataSlicesSlice,
         TechnologiesDocument,
         TechnologiesDocumentData,
         TechnologiesCardDocument,
         TechnologiesCardDocumentData,
         TechnologiesCardDocumentDataTechnologiesDataItem,
         AllDocumentTypes,
         AboutMeBlockSlice,
         AboutMeBlockSliceDefaultPrimary,
         AboutMeBlockSliceVariation,
         AboutMeBlockSliceDefault,
         ContactMeBlockSlice,
         ContactMeBlockSliceDefaultPrimary,
         ContactMeBlockSliceVariation,
         ContactMeBlockSliceDefault,
         TechnologiesBlockSlice,
         TechnologiesBlockSliceDefaultPrimaryCardsItem,
         TechnologiesBlockSliceDefaultPrimary,
         TechnologiesBlockSliceVariation,
         TechnologiesBlockSliceDefault,
         TextBlockSlice,
         TextBlockSliceDefaultPrimaryButtonsGroupItem,
         TextBlockSliceDefaultPrimary,
         TextBlockSliceVariation,
         TextBlockSliceDefault,
      };
   }
}
