// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
   about_me_block: dynamic(() => import('./AboutMeBlock')),
   contact_me_block: dynamic(() => import('./ContactMeBlock')),
   projects_accordion_block: dynamic(() => import('./ProjectsAccordionBlock')),
   technologies_block: dynamic(() => import('./TechnologiesBlock')),
   text_block: dynamic(() => import('./TextBlock')),
};
