// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
   main_banner: dynamic(() => import('./MainBanner')),
   about_me_block: dynamic(() => import('./AboutMeBlock')),
   contact_me_block: dynamic(() => import('./ContactMeBlock')),
   technologies_block: dynamic(() => import('./TechnologiesBlock')),
   projects_accordion_block: dynamic(() => import('./ProjectsAccordionBlock')),
};
